=== warunap/haaprojects/HAAProject_DataConvert/src/main/test/haaconverter.dtd
<!-- 
Author:Geln Yang 
  Date:2008-10-24

Data Convert Configuration Definition
-->
<!ELEMENT converter (component)>
<!ATTLIST converter name CDATA #REQUIRED>
<!ATTLIST converter batched (true|false) "true">
<!ATTLIST converter batchSize CDATA  "100">
<!ATTLIST converter charset CDATA "UTF-8">
<!ATTLIST converter hasLineFlag (true|false) "true">

<!ELEMENT component (component|line)+ >
<!ATTLIST component name CDATA #REQUIRED>
<!ATTLIST component className CDATA "java.util.HashMap">
<!ATTLIST component occurs (once|none_once|many|none_many) "none_many">
<!ATTLIST component lineSize CDATA #IMPLIED>

<!ELEMENT line (property*)>

<!ATTLIST line name CDATA #REQUIRED>
<!ATTLIST line startKey CDATA #IMPLIED>
<!ATTLIST line hasStartKey (true|false) "true">
<!ATTLIST line split CDATA #IMPLIED>
<!ATTLIST line className CDATA "java.util.HashMap">
<!ATTLIST line fixed (true|false) "true">
<!ATTLIST line length CDATA #IMPLIED>
<!ATTLIST line occurs (once|none_once|many|none_many) "none_many">
<!ATTLIST line ignoreMore (true|false) "false">
<!ATTLIST line trans (true|false) "false">
<!ATTLIST line tableName CDATA #IMPLIED>

<!ELEMENT property EMPTY>

<!ATTLIST property name CDATA #REQUIRED>
<!ATTLIST property desc CDATA #IMPLIED>
<!ATTLIST property length CDATA #IMPLIED>
<!ATTLIST property maxLength CDATA #IMPLIED>
<!ATTLIST property align (left|right) "left">
<!ATTLIST property type CDATA "String">
<!ATTLIST property format CDATA #IMPLIED>
<!ATTLIST property precision CDATA #IMPLIED>
<!ATTLIST property scale CDATA #IMPLIED>
<!ATTLIST property pattern CDATA #IMPLIED>
<!ATTLIST property defValue CDATA #IMPLIED>
<!ATTLIST property needRadixPoint (false|true) "false">
<!ATTLIST property needFillZero (false|true) "false">
<!ATTLIST property settled (false|true) "false">
<!ATTLIST property optional (false|true) "false">
<!ATTLIST property trim (false|true) "false">
<!ATTLIST property start CDATA #IMPLIED>
<!ATTLIST property end CDATA #IMPLIED>

=== warunap/haaprojects/HAAProject_DataConvert/src/main/test/config/stockData.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE converter SYSTEM "haaconverter.dtd">
<converter name="stockData" charset="GB2312">
	<component name="root" className="java.util.HashMap">
		<line name="header" hasStartKey="false" className="java.util.HashMap" fixed="false" split="," occurs="once">
			<property name="date" length="10" trim="true" />
			<property name="code" length="10" trim="true" />
			<property name="name" length="50" trim="true" />
			<property name="closingPrice" length="100" trim="true" />
			<property name="highestPrice" length="100" trim="true" />
			<property name="lowestPrice" length="100" trim="true" />
			<property name="openingPrice" length="100" trim="true" />
			<property name="preClosingPrice" length="100" trim="true" />
			<property name="changeAmount" length="100" trim="true" />
			<property name="changePercent" length="100" trim="true" />
			<property name="handsRate" length="100" trim="true" />
			<property name="tradeCount" length="100" trim="true" />
			<property name="tradeAmount" length="100" trim="true" />
			<property name="totalMarketValue" length="100" trim="true" />
			<property name="currentMarketValue" length="100" trim="true" />
		</line>
		<component name="details" className="java.util.ArrayList">
			<line name="item" hasStartKey="false" className="java.util.HashMap" fixed="false" split="," occurs="many" tableName="STOCK_DATA">
				<property name="date" length="10" trim="true" />
				<property name="code" length="10" trim="true" />
				<property name="name" length="50" trim="true" />
				<property name="closingPrice" precision="12" scale="4" needRadixPoint="true" />
				<property name="highestPrice" precision="12" scale="4" needRadixPoint="true" />
				<property name="lowestPrice" precision="12" scale="4" needRadixPoint="true" />
				<property name="openingPrice" precision="12" scale="4" needRadixPoint="true" />
				<property name="preClosingPrice" precision="12" scale="4" needRadixPoint="true" />
				<property name="changeAmount" precision="12" scale="4" needRadixPoint="true" />
				<property name="changePercent" precision="12" scale="4" needRadixPoint="true" />
				<property name="handsRate" precision="12" scale="4" needRadixPoint="true" />
				<property name="tradeCount" precision="20" scale="3" needRadixPoint="true" />
				<property name="tradeAmount" precision="20" scale="3" needRadixPoint="true" />
				<property name="totalMarketValue" precision="20" scale="3" needRadixPoint="true" />
				<property name="currentMarketValue" precision="20" scale="3" needRadixPoint="true" />
			</line>
		</component>
	</component>
</converter>
